Repository Code-Institute-Community/ci-hackathon-app, pull requests merged in 2020-10, with the labels that each got.

#5 Migrate from env.py to python-dotenv
  .env_sample
  .gitignore
  main/settings.py
  requirements.txt
Labels: documentation

#6 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#7 Update README with further information
  README.md
Labels: documentation

#8 Add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#9 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#10 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#11 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#12 Correct Code-Of-Contact email address format
  CODE_OF_CONDUCT.md
Labels: documentation

#13 Update README documentation
  README.md
Labels: documentation

#14 Include CI and Hacktoberfest Code-of-Conducts
  CODE_OF_CONDUCT.md
Labels: documentation

#15 Documentation
  static/img/hackathon-ERD.png
  static/img/hackathon-use-case--judge.png
  static/img/hackathon-use-case--organizer.png
  static/img/hackathon-use-case--participant.png
Labels: documentation

#16 Subcategorize documentation images in static dir
  static/img/documentation/flow-chart.png
  static/img/documentation/hackathon-ERD.png
  static/img/documentation/hackathon-use-case--judge.png
  static/img/documentation/hackathon-use-case--organizer.png
  static/img/documentation/hackathon-use-case--participant.png
Labels: documentation

#50 Add some wireframes for desktop view
  static/wireframes/hackathon-page--desktop.png
  static/wireframes/judging-page--desktop.png
  static/wireframes/langing-page--desktop.png
  static/wireframes/login-page--desktop.png
  static/wireframes/profile-page--desktop.png
  static/wireframes/register-page--desktop.png
Labels: documentation

#52 #M03: Include base setup files and static
  .env_sample
  home/__init__.py
  home/apps.py
  home/migrations/__init__.py
  home/templates/home/index.html
  home/urls.py
  home/views.py
  main/settings.py
  main/urls.py
  profiles/__init__.py
  profiles/apps.py
  profiles/forms.py
  profiles/migrations/__init__.py
  profiles/models.py
  profiles/templates/profiles/profile.html
  profiles/urls.py
  profiles/views.py
  static/css/style.css
  static/img/ci-favicon.png
  static/img/ci-logo.svg
  static/js/script.js
  templates/base.html
  templates/includes/footer.html
  templates/includes/messages.html
  templates/includes/navbar.html
Labels: hacktoberfest, help wanted

#71 Feature/m06 participant easy setup
  .gitignore
  setup.bat
  setup.sh
Labels: hacktoberfest-accepted

#72 #M05 Creating Hackathon Database Models
  .gitignore
  hackathon/__init__.py
  hackathon/admin.py
  hackathon/apps.py
  hackathon/migrations/0001_initial.py
  hackathon/migrations/0002_auto_20201015_1936.py
  hackathon/migrations/0003_auto_20201015_2020.py
  hackathon/migrations/0004_auto_20201015_2224.py
  hackathon/migrations/0005_auto_20201016_1951.py
  hackathon/migrations/0006_auto_20201016_2050.py
  hackathon/migrations/0007_auto_20201017_1148.py
  hackathon/migrations/__init__.py
  hackathon/models.py
  hackathon/tests/__init__.py
  hackathon/tests/test_models.py
  hackathon/urls.py
  hackathon/views.py
  main/settings.py
  main/urls.py
Labels: hacktoberfest-accepted

#76 #P04 As Participant, I would like to see a list of any upcoming Hackathons.
  hackathon/templates/hackathon/hackathon_list.html
  hackathon/templates/hackathon/includes/hackathon_card.html
  hackathon/templates/hackathon/includes/paginator.html
  hackathon/tests/test_models.py
  hackathon/tests/test_views.py
  hackathon/urls.py
  hackathon/views.py
  static/css/style.css
  templates/includes/navbar.html
Labels: hacktoberfest-accepted

#81 Add highest_score field to HackProjectScoreCategory model
  hackathon/migrations/0008_hackprojectscorecategory_highest_score.py
  hackathon/migrations/0009_auto_20201018_1829.py
  hackathon/models.py
  hackathon/tests/test_models.py
Labels: hacktoberfest-accepted

#89 Additional PR in relation to User authentication ~ #83
  accounts/models.py
  templates/includes/navbar.html
Labels: hacktoberfest-accepted

#98 #P03. As Participant, I would like to update my profile.
  accounts/forms.py
  accounts/migrations/0003_auto_20201023_1201.py
  accounts/models.py
  accounts/templates/accounts/edit_profile.html
  accounts/urls.py
  accounts/views.py
  main/urls.py
  profiles/templates/profiles/profile.html
  static/css/style.css
Labels: hacktoberfest-accepted

#106 #A03. As Admin, I would like to update existing Hackathon events.
  hackathon/forms.py
  hackathon/templates/hackathon/create-event.html
  hackathon/templates/hackathon/includes/hackathon_card.html
  hackathon/urls.py
  hackathon/views.py
Labels: hacktoberfest-accepted

#103 S08 judging
  .gitignore
  hackathon/lists.py
  hackathon/migrations/0017_auto_20201025_1211.py
  hackathon/migrations/0018_auto_20201025_1933.py
  hackathon/migrations/0021_merge_20201029_1407.py
  hackathon/migrations/0022_hackathon_judging_status.py
  hackathon/models.py
  hackathon/static/hackathon/css/hackathon.css
  hackathon/templates/hackathon/judging.html
  hackathon/templatetags/__init__.py
  hackathon/templatetags/my_tags.py
  hackathon/urls.py
  hackathon/views.py
Labels: hacktoberfest-accepted

#110 #M09 Participant profile page
  .gitignore
  Pipfile.lock
  profiles/templates/profiles/profile.html
  static/css/profile.css
  static/css/style.css
  static/img/profiles/profile_cat.png
  templates/base.html
Labels: hacktoberfest-accepted

#112 #M01. Judging Automation
  hackathon/views.py
Labels: hacktoberfest-accepted

#116 Add allauth styles
  accounts/templates/accounts/edit_profile.html
  static/css/allauthstyles.css
  static/css/profile.css
  templates/allauth/account/account_inactive.html
  templates/allauth/account/base.html
  templates/allauth/account/email.html
  templates/allauth/account/email_confirm.html
  templates/allauth/account/login.html
  templates/allauth/account/logout.html
  templates/allauth/account/password_change.html
  templates/allauth/account/password_reset.html
  templates/allauth/account/password_reset_done.html
  templates/allauth/account/password_reset_from_key.html
  templates/allauth/account/password_reset_from_key_done.html
  templates/allauth/account/password_set.html
  templates/allauth/account/signup.html
  templates/allauth/account/signup_closed.html
  templates/allauth/account/verification_sent.html
  templates/allauth/account/verified_email_required.html
Labels: hacktoberfest-accepted
